name: "🐛 Bug report"
description: "Create a bug report to help us improve"
title: "Bug: "
labels: ["bug"]
body:
  - type: "markdown"
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: "textarea"
    id: "bug"
    attributes:
      label: "Describe the bug"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: "textarea"
    id: "steps"
    attributes:
      label: "Steps to reproduce"
      description: "Describe how to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: "checkboxes"
    id: "os"
    attributes:
      label: "Which operating systems have you used?"
      description: "You may select more than one."
      options:
        - label: "macOS"
        - label: "Windows"
        - label: "Linux"
  - type: "dropdown"
    id: "browser"
    attributes:
      multiple: true
      label: "Browsers"
      description: "Select the browsers where the issue can be reproduced (that you know of)."
      options:
        - "All"
        - "Chrome"
        - "Firefox"
        - "Safari"
        - "Edge"
        - "Opera"
        - "Other (add environment context)"
  - type: "input"
    id: "environment"
    attributes:
      label: "Environment or branch this occurs in"
      description: "If you know the environment or branch this occurs in, please add it here."
