blank_issues_enabled: false
contact_links:
  - name: "GitHub Discussions"
    url: "https://github.com/orgs/TMCB-SPACE/discussions"
    about: "Please ask and answer questions here."
    icon: "github"
